spring:
  application:
    name: flipnote

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  data:
    redis:
      host:
      password:
      port:

management:
  endpoints:
    web:
      exposure:
        include:
          - health

jwt:
  secret:
  access-token-expiration: 1h
  refresh-token-expiration: 7d

async:
  core-pool-size: 4
  max-pool-size: 10
  queue-capacity: 100

resend:
  api-key:
  from-email: onboarding@resend.dev
