spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flipnote?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: dummy_secret

resend:
  api-key: dummy_api_key
